### ISSUE TITLE
Can you share non compiled files

### ISSUE THREAD

**Issue by davidyye** [haqbany/Bigtreetouch-SKR-Mini-E3V3.0#1]
hello haqbany
Can you share the non-compiled marlin files of firmwares (platformio.ini, configuration-adv,configuration...).
 thx a lot

**Comment by haqbany** [comment]
Hi sure but I'm still working on the source file I will be sharing it with a few days.

**Comment by haqbany** [comment]
Hi files is uploaded

**Comment by haqbany** [comment]
Hi I have add the source code , and I have release now firmware update.

Best Regards
Rashid
