### ISSUE TITLE
Bed Leveling Collision

### ISSUE THREAD

**Issue by SonomaGTS** [haqbany/Bigtreetouch-SKR-Mini-E3V3.0#4]
On my Ender 3 Pro (2021 release) when I initiate the bed leveling the parts fan housing smacks into the belt tensioning mount screw on the far end ONLY on the first row. Every row after that it does not hit. Curious if the probing speed is to blame from the initial start or what could be causing that.

**Comment by haqbany** [comment]
Hi , is not the probe speed for sure , unless you have different fan design . I have no complaint regarding this issue from anyone, try to move the fan to different angle if you still want to use same firmware.Best regards Rashid Sent from my iPhoneOn 19 Dec 2022, at 10:21 AM, SonomaGTS ***@***.***> wrote:﻿
On my Ender 3 Pro (2021 release) when I initiate the bed leveling the parts fan housing smacks into the belt tensioning mount screw on the far end ONLY on the first row. Every row after that it does not hit. Curious if the probing speed is to blame from the initial start or what could be causing that.

**Comment by SonomaGTS** [comment]
I had loosen and retighten while pushing over on the inner screw on the tension mount. The fan housing now clears the screw during the mesh sequence but just barely. I noticed the 25 point system has that end of the bed set to 248 on the x axis. I believe for future release maybe changing that to 246 might help with any possible irregularities in build quality of the machine such as I must have had with mine.

**Comment by haqbany** [comment]
Thank you , I put this in the new firmware Settings. What printer you have ? Sent from my iPhoneOn 21 Dec 2022, at 7:36 AM, SonomaGTS ***@***.***> wrote:﻿
I had loosen and retighten while pushing over on the inner screw on the tension mount. The fan housing now clears the screw during the mesh sequence but just barely. I noticed the 25 point system has that end of the bed set to 248 on the x axis. I believe for future release maybe changing that to 246 might help with any possible irregularities in build quality of the machine such as I must have had with mine.

**Comment by SonomaGTS** [comment]
This is a 2021 version Ender 3 Pro.

**Comment by haqbany** [comment]
make sense  This is a 2021 version Ender 3 Pro has little difference than
ender 3v2
